dataset_synthetic: dataset_synthetic
dataset_test: dataset_test
fonts: fonts
models_best: models_best
models_save: models_save
pdf_files: pdf_files
vocab_category:
  1_digits: 0123456789
  2_punctuation: '!"''#%&()*+,-./:;<=>?@[\]^_{|}~№°'
  3_currency: $£€¥¢₽
  4_ru_char: АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя
vocab_replace:
  '`': ''''
  «: '"'
  ´: ''''
  »: '"'
  –: '-'
  —: '-'
  ―: '-'
  ‘: ''''
  ’: ''''
  “: '"'
  ”: '"'
  „: '"'
  …: '...'
